# Generated by Django 3.1.7 on 2021-03-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_auto_20210331_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='datalog',
            old_name='log_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='statuslog',
            old_name='status_id',
            new_name='id',
        ),
    ]
